/**
 * JSOS SwiftShader Platform Bridge — Memory
 *
 * Routes SwiftShader memory allocation requests to the JSOS TypeScript VMM.
 * SwiftShader calls these functions during shader compilation and render-
 * target allocation.
 *
 * In Phase 8 this file is a stub compiled alongside SwiftShader when the
 * lib/swiftshader/ submodule is checked out.  The JSOS Makefile links it as
 * part of the jsos_swiftshader_platform.a static archive.
 *
 * C-callable symbols declared in include/jsos_platform.h (to be added when
 * SwiftShader is checked out) match the extern declarations SwiftShader's
 * Platform/ layer expects from its embedding application.
 */

#include <stddef.h>
#include <stdint.h>

// ── JSOS kernel C bindings (generated by quickjs_binding.c) ──────────────

extern "C" {
  // Phase 4 VMM — allocate a region of virtual address space
  // prot: 0=none 1=r 2=rw 3=rwx
  uint32_t jsos_vmm_alloc(uint32_t size, uint32_t alignment);
  uint32_t jsos_vmm_alloc_exec(uint32_t size);         // PROT_EXEC (JIT shaders)
  void     jsos_vmm_free(uint32_t addr, uint32_t size);
}

// ── SwiftShader platform implementation ──────────────────────────────────

extern "C" {

/**
 * Allocate `size` bytes with at least `alignment` byte alignment.
 * Called by SwiftShader for shader programs, uniform buffers, etc.
 */
void* sw_allocateMemory(size_t size, size_t alignment) {
  (void)alignment;  // JSOS VMM always 4KB-aligned
  uint32_t addr = jsos_vmm_alloc((uint32_t)size, (uint32_t)alignment);
  return addr ? reinterpret_cast<void*>(addr) : nullptr;
}

/**
 * Free a previously allocated block.
 */
void sw_freeMemory(void* ptr, size_t size) {
  if (ptr) jsos_vmm_free(reinterpret_cast<uint32_t>(ptr), (uint32_t)size);
}

/**
 * Allocate an executable (PROT_EXEC) buffer for JIT-compiled shaders.
 * SwiftShader compiles SPIR-V shaders to native x86 machine code at
 * pipeline-creation time and needs RWX pages for the output.
 */
void* sw_allocateJITBuffer(size_t size) {
  uint32_t addr = jsos_vmm_alloc_exec((uint32_t)size);
  return addr ? reinterpret_cast<void*>(addr) : nullptr;
}

} // extern "C"
