#!/usr/bin/env node
/**
 * build-wasm.js — AssemblyScript → WASM → C header pipeline
 *
 * For each module in src/wasm/:
 *   1. Run `asc src/wasm/NAME.ts --outFile build/wasm/NAME.wasm -O3 --runtime stub --noAssert`
 *   2. Read the .wasm file
 *   3. Emit it as a C uint8_t array in src/kernel/wasm_blobs.h
 *   4. Also emit base64-encoded blobs as a JS file for the bundle
 *
 * Falls back gracefully if AssemblyScript is not installed.
 */

'use strict';

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT    = path.resolve(__dirname, '..');
const SRC_DIR = path.join(ROOT, 'src', 'wasm');
const OUT_DIR = path.join(ROOT, 'build', 'wasm');
const BLOBS_H = path.join(ROOT, 'src', 'kernel', 'wasm_blobs.h');
const BLOBS_JS = path.join(ROOT, 'src', 'os', 'process', 'wasm-blobs.gen.js');

const MODULES = ['crypto', 'sort', 'compress', 'render', 'memory-ops'];

// ── Check AssemblyScript available ──────────────────────────────────────────

function findAsc() {
  // Try local install first
  const localAsc = path.join(ROOT, 'node_modules', '.bin', 'asc');
  if (fs.existsSync(localAsc + '.cmd') || fs.existsSync(localAsc)) {
    return fs.existsSync(localAsc + '.cmd') ? localAsc + '.cmd' : localAsc;
  }
  try { execSync('asc --version', { stdio: 'ignore' }); return 'asc'; } catch (_) {}
  return null;
}

// ── Compile one module ───────────────────────────────────────────────────────

function compileModule(asc, name) {
  const src = path.join(SRC_DIR, name + '.ts');
  const out = path.join(OUT_DIR, name + '.wasm');
  if (!fs.existsSync(src)) {
    console.warn(`  ⚠  ${name}.ts not found, skipping`);
    return null;
  }
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const cmd = [
    asc,
    src,
    '--outFile', out,
    '--optimizeLevel', '3',
    '--shrinkLevel', '1',
    '--runtime', 'stub',
    '--noAssert',
    '--target', 'release',
    '--use', 'Math=JSMath',
  ].join(' ');

  try {
    console.log(`  Compiling ${name}.ts → build/wasm/${name}.wasm`);
    execSync(cmd, { cwd: ROOT, stdio: ['ignore', 'pipe', 'pipe'] });
    const bytes = fs.readFileSync(out);
    console.log(`    ✓  ${bytes.length} bytes`);
    return bytes;
  } catch (err) {
    const msg = err.stderr ? err.stderr.toString().trim() : err.message;
    console.error(`  ✗  ${name} compilation failed:\n${msg}`);
    return null;
  }
}

// ── Emit wasm_blobs.h ────────────────────────────────────────────────────────

function cIdentifier(name) {
  return name.replace(/-/g, '_');
}

function emitCHeader(blobs) {
  const lines = [
    '/* wasm_blobs.h — AUTO-GENERATED by scripts/build-wasm.js — DO NOT EDIT */',
    '#pragma once',
    '#include <stdint.h>',
    '',
  ];

  for (const [name, buf] of Object.entries(blobs)) {
    const ident = cIdentifier(name);
    const hexBytes = Array.from(buf).map(b => '0x' + b.toString(16).padStart(2, '0')).join(', ');
    lines.push(`static const uint8_t wasm_blob_${ident}[] = { ${hexBytes} };`);
    lines.push(`static const uint32_t wasm_blob_${ident}_len = ${buf.length}u;`);
    lines.push('');
  }

  lines.push('/* Module count */')
  lines.push(`#define WASM_BLOB_COUNT ${Object.keys(blobs).length}`);
  lines.push('');
  lines.push('/* Name / pointer / length table for boot-time init */');
  lines.push('typedef struct { const char *name; const uint8_t *data; uint32_t len; } WasmBlobEntry;');
  lines.push('static const WasmBlobEntry wasm_blob_table[] = {');
  for (const [name, buf] of Object.entries(blobs)) {
    const ident = cIdentifier(name);
    lines.push(`  { "${name}", wasm_blob_${ident}, ${buf.length}u },`);
  }
  lines.push('};');
  lines.push('');

  fs.mkdirSync(path.dirname(BLOBS_H), { recursive: true });
  fs.writeFileSync(BLOBS_H, lines.join('\n'));
  console.log(`  Wrote ${BLOBS_H}`);
}

// ── Emit wasm-blobs.gen.js for the TypeScript bundle ──────────────────────

function emitJsBlobs(blobs) {
  const lines = [
    '/* wasm-blobs.gen.js — AUTO-GENERATED by scripts/build-wasm.js — DO NOT EDIT */',
    '/* Embedded WASM modules as base64 strings. Loaded at boot by wasm-loader.ts  */',
    "'use strict';",
    '',
    '// @ts-nocheck',
    'const wasmBlobs = {',
  ];

  for (const [name, buf] of Object.entries(blobs)) {
    lines.push(`  ${JSON.stringify(name)}: ${JSON.stringify(buf.toString('base64'))},`);
  }

  lines.push('};');
  lines.push('');
  lines.push('if (typeof module !== "undefined") module.exports = wasmBlobs;');
  lines.push('');

  fs.mkdirSync(path.dirname(BLOBS_JS), { recursive: true });
  fs.writeFileSync(BLOBS_JS, lines.join('\n'));
  console.log(`  Wrote ${BLOBS_JS}`);
}

// ── Stub blobs (when asc not available) ─────────────────────────────────────

function makeStubBlob(name) {
  // Minimal valid WASM module: magic + version + empty
  return Buffer.from([0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00]);
}

// ── Main ─────────────────────────────────────────────────────────────────────

function main() {
  console.log('=== JSOS WASM Build Pipeline ===');

  const asc = findAsc();
  if (!asc) {
    console.warn('  ⚠  AssemblyScript (asc) not found — emitting stub blobs.');
    console.warn('     Run: npm install  to install assemblyscript@^0.27.0');
    const blobs = {};
    for (const name of MODULES) blobs[name] = makeStubBlob(name);
    emitCHeader(blobs);
    emitJsBlobs(blobs);
    console.log('  Stub blobs written. Build will still succeed (no-op WASM at runtime).');
    return;
  }

  console.log(`  asc found: ${asc}`);
  const blobs = {};
  let ok = 0;
  for (const name of MODULES) {
    const buf = compileModule(asc, name);
    if (buf) { blobs[name] = buf; ok++; }
    else      { blobs[name] = makeStubBlob(name); }
  }

  emitCHeader(blobs);
  emitJsBlobs(blobs);

  console.log(`\n=== WASM build complete: ${ok}/${MODULES.length} modules compiled ===`);
  if (ok < MODULES.length) {
    console.warn('  Some modules used stub blobs — WASM acceleration disabled for those.');
  }
}

main();
