#!/usr/bin/env node
/**
 * embed-rom.js
 * Reads files from resources/ and generates src/os/fs/romfs.ts.
 * The generated file exports installRomFiles(fs) which writes each file
 * into the normal in-memory filesystem at boot — exactly like the files
 * written in initializeDefaultFS().
 *
 * Run via: npm run embed:rom
 *
 * Manifest:
 *   resources/bible.txt  →  /home/user/bible.txt
 */

const fs   = require('fs');
const path = require('path');

const RESOURCES_DIR = path.join(__dirname, '..', 'resources');
const OUTPUT        = path.join(__dirname, '..', 'src', 'os', 'fs', 'romfs.ts');

// Map of local filename → install path inside the OS filesystem
const ROM_MANIFEST = [
  { file: 'bible.txt', installPath: '/home/user/bible.txt' },
];

console.log('Generating ROM filesystem installer (romfs.ts)...');

const entries = [];
for (const entry of ROM_MANIFEST) {
  const localPath = path.join(RESOURCES_DIR, entry.file);
  if (!fs.existsSync(localPath)) {
    console.warn(`  (skip) ${entry.file} not found in resources/`);
    continue;
  }
  const raw = fs.readFileSync(localPath, 'utf8');
  const content = raw
    .replace(/\r\n/g, '\n')
    .replace(/\\/g,  '\\\\')
    .replace(/`/g,   '\\`')
    .replace(/\$\{/g, '\\${');
  entries.push({ installPath: entry.installPath, content });
  console.log(`  + ${entry.installPath}  (${(raw.length / 1024).toFixed(1)} KB)`);
}

const installLines = entries.map(e =>
  `  fs.writeFile('${e.installPath}', \`${e.content}\`);`
).join('\n\n');

const ts = `/**
 * JSOS ROM File Installer — auto-generated by scripts/embed-rom.js
 *
 * DO NOT EDIT.  Regenerate with:  npm run embed:rom
 *
 * Writes bundled resource files into the in-memory filesystem at boot,
 * exactly like the files installed in initializeDefaultFS().
 *
 * Installed paths:
${entries.map(e => ` *   ${e.installPath}`).join('\n')}
 */
import type { FileSystem } from './filesystem.js';

export function installRomFiles(fs: FileSystem): void {
${installLines || '  // no resources embedded'}
}
`;

fs.writeFileSync(OUTPUT, ts, 'utf8');
const kb = (fs.statSync(OUTPUT).size / 1024).toFixed(1);
console.log(`Done. ${OUTPUT} written (${kb} KB, ${entries.length} file(s) embedded).`);
